name: imgcolor_env
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - fastapi==0.115.12
      - mlflow==3.1.1
      - opencv-python==4.9.0.80
      - tensorflow==2.19.0
      - keras==3.10.0
      - pandas==2.3.1
      - numpy==2.1.3
      - scikit-learn==1.7.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorboard==2.19.0
      - uvicorn==0.34.3
      - typer==0.16.0
      - rich==14.0.0
      - docker==7.1.0
      - requests==2.32.4
      - pyzmq==27.0.0
      - python-dotenv==1.1.0
      - werkzeug==3.1.3
